# Generated by CMake 3.5.0

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget csirocsa qsastime plplot plplotcxx plplotf95c plplotf95 plplotwxwidgets mem null ps svg wingcc wxwidgets xfig plf95demolib)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# The installation prefix configured by this project.
set(_IMPORT_PREFIX "C:/Program Files (x86)/plplot")

# Create imported target csirocsa
add_library(csirocsa SHARED IMPORTED)

# Create imported target qsastime
add_library(qsastime SHARED IMPORTED)

# Create imported target plplot
add_library(plplot SHARED IMPORTED)

set_target_properties(plplot PROPERTIES
  INTERFACE_LINK_LIBRARIES "csirocsa;qsastime"
)

# Create imported target plplotcxx
add_library(plplotcxx SHARED IMPORTED)

set_target_properties(plplotcxx PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplot"
)

# Create imported target plplotf95c
add_library(plplotf95c SHARED IMPORTED)

set_target_properties(plplotf95c PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplot"
)

# Create imported target plplotf95
add_library(plplotf95 SHARED IMPORTED)

set_target_properties(plplotf95 PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplotf95c"
)

# Create imported target plplotwxwidgets
add_library(plplotwxwidgets SHARED IMPORTED)

set_target_properties(plplotwxwidgets PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplot;plplotcxx;\$<\$<CONFIG:DEBUG>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxmsw30ud_core.a>;\$<\$<NOT:\$<CONFIG:DEBUG>>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxmsw30u_core.a>;\$<\$<CONFIG:DEBUG>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxbase30ud.a>;\$<\$<NOT:\$<CONFIG:DEBUG>>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxbase30u.a>;\$<\$<CONFIG:DEBUG>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxpngd.a>;\$<\$<NOT:\$<CONFIG:DEBUG>>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxpng.a>;\$<\$<CONFIG:DEBUG>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxtiffd.a>;\$<\$<NOT:\$<CONFIG:DEBUG>>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxtiff.a>;\$<\$<CONFIG:DEBUG>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxjpegd.a>;\$<\$<NOT:\$<CONFIG:DEBUG>>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxjpeg.a>;\$<\$<CONFIG:DEBUG>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxzlibd.a>;\$<\$<NOT:\$<CONFIG:DEBUG>>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxzlib.a>;\$<\$<CONFIG:DEBUG>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxregexud.a>;\$<\$<NOT:\$<CONFIG:DEBUG>>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxregexu.a>;\$<\$<CONFIG:DEBUG>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxexpatd.a>;\$<\$<NOT:\$<CONFIG:DEBUG>>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxexpat.a>;winmm;comctl32;rpcrt4;wsock32"
)

# Create imported target mem
add_library(mem MODULE IMPORTED)

set_target_properties(mem PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplot"
)

# Create imported target null
add_library(null MODULE IMPORTED)

set_target_properties(null PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplot"
)

# Create imported target ps
add_library(ps MODULE IMPORTED)

set_target_properties(ps PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplot"
)

# Create imported target svg
add_library(svg MODULE IMPORTED)

set_target_properties(svg PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplot"
)

# Create imported target wingcc
add_library(wingcc MODULE IMPORTED)

set_target_properties(wingcc PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplot;D:/CodeBlocks/MinGW/lib/libgdi32.a;D:/CodeBlocks/MinGW/lib/libcomdlg32.a"
)

# Create imported target wxwidgets
add_library(wxwidgets MODULE IMPORTED)

set_target_properties(wxwidgets PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplot;\$<\$<CONFIG:DEBUG>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxmsw30ud_core.a>;\$<\$<NOT:\$<CONFIG:DEBUG>>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxmsw30u_core.a>;\$<\$<CONFIG:DEBUG>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxbase30ud.a>;\$<\$<NOT:\$<CONFIG:DEBUG>>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxbase30u.a>;\$<\$<CONFIG:DEBUG>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxpngd.a>;\$<\$<NOT:\$<CONFIG:DEBUG>>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxpng.a>;\$<\$<CONFIG:DEBUG>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxtiffd.a>;\$<\$<NOT:\$<CONFIG:DEBUG>>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxtiff.a>;\$<\$<CONFIG:DEBUG>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxjpegd.a>;\$<\$<NOT:\$<CONFIG:DEBUG>>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxjpeg.a>;\$<\$<CONFIG:DEBUG>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxzlibd.a>;\$<\$<NOT:\$<CONFIG:DEBUG>>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxzlib.a>;\$<\$<CONFIG:DEBUG>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxregexud.a>;\$<\$<NOT:\$<CONFIG:DEBUG>>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxregexu.a>;\$<\$<CONFIG:DEBUG>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxexpatd.a>;\$<\$<NOT:\$<CONFIG:DEBUG>>:D:/wxWidgets-3.0.2/lib/gcc_lib/libwxexpat.a>;winmm;comctl32;rpcrt4;wsock32"
)

# Create imported target xfig
add_library(xfig MODULE IMPORTED)

set_target_properties(xfig PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplot"
)

# Create imported target plf95demolib
add_library(plf95demolib STATIC IMPORTED)

set_target_properties(plf95demolib PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplotf95"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/export_plplot-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
